-- Remove and (re)create database 'FREERIDER_DB', which clears all
-- prior tables and data
-- 
DROP SCHEMA IF EXISTS FREERIDER_DB;
CREATE SCHEMA IF NOT EXISTS FREERIDER_DB;
USE FREERIDER_DB;

CREATE TABLE IF NOT EXISTS CUSTOMER (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(60) DEFAULT NULL,
    `CONTACT` VARCHAR(60) DEFAULT NULL,
    `STATUS` ENUM('Active', 'InRegistration', 'Terminated') DEFAULT NULL,
    PRIMARY KEY (ID)
);
-- ALTER TABLE CUSTOMER AUTO_INCREMENT = 1000;

CREATE TABLE IF NOT EXISTS VEHICLE (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `MAKE` VARCHAR(60) DEFAULT NULL,
    `MODEL` VARCHAR(60) DEFAULT NULL,
    `SEATS` INT DEFAULT '4',
    `CATEGORY` ENUM('Sedan', 'SUV', 'Convertible', 'Van', 'Bike') DEFAULT NULL,
    `POWER` ENUM('Gasoline', 'Diesel', 'Electric', 'Hybrid', 'Hydrogen') DEFAULT NULL,
    `STATUS` ENUM('Active', 'Serviced', 'Terminated') DEFAULT NULL,
    PRIMARY KEY (ID)
);
-- ALTER TABLE VEHICLE AUTO_INCREMENT = 8000;

CREATE TABLE IF NOT EXISTS RESERVATION (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CUSTOMER_ID` INT NOT NULL,
    `VEHICLE_ID` INT NOT NULL,
    `RBEGIN` DATETIME DEFAULT NULL,
    `REND` DATETIME DEFAULT NULL,
    `PICKUP` VARCHAR(48) DEFAULT NULL,
    `DROPOFF` VARCHAR(48) DEFAULT NULL,
    `STATUS` ENUM('Inquired', 'InquiryConfirmed', 'Booked', 'Cancelled') DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(ID)
);
-- ALTER TABLE RESERVATION AUTO_INCREMENT = 220000;
